name: Run Robinhood Temp Scanner

on:
  schedule:
    - cron: "10 */1 * * *"  #runs every 1 hour
  workflow_dispatch:        # allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver (matching Chrome)
        uses: nanasess/setup-chromedriver@v2

      - name: Run script
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        run: |
          python Robinhood.py
